### PR TITLE
initial proposal for front page counting up from gov 

### PR DESCRIPTION
**Pull request by andrewbolster**
(needs about update)

[preview](https://www.dropbox.com/s/xhhgc2dcx4q9374/Screenshot%202020-01-12%2014.58.04.png)

### CODE REVIEW

**Comment by philtweir** [comment]
Actually, I have also a branch for our now-existing government - great minds! Think it is worth having the (now static) total clear so maybe doesn't need stripped so far back?

**Comment by philtweir** [comment]
The other idea that came up over the weekend, as this is now a 3 year old mandate, is to tweak to also count days since an election. Thoughts?

**Comment by andrewbolster** [comment]
I was gonna sit down and do a horizontal timeline of how long it's been open/closed since launch. 

Given the timing I'm gonna merge this as a stopgap and then we can tear away at it

**Comment by philtweir** [comment]
Good idea +1

**Comment by bhamill638** [comment]
Much nicer than my PR! :D

**Pull request merged**
